import React, { ReactNode } from 'react';
interface VideoProps {
    src: string;
    poster?: string;
    onDuration?: (duration: number) => void;
    onEnded?: () => void;
    isPause?: boolean;
    spacebarPlay?: boolean;
    className?: string;
    autoPlay?: boolean;
    showControls?: boolean;
    showPlayPause?: boolean;
    showProgress?: boolean;
    showVolume?: boolean;
    showTime?: boolean;
    showFullscreen?: boolean;
    showDownload?: boolean;
    showSeekButtons?: boolean;
    playIcon?: string | ReactNode;
    pauseIcon?: string | ReactNode;
    fullscreenIcon?: string | ReactNode;
    downloadIcon?: string | ReactNode;
    volumeIcon?: string | ReactNode;
    muteIcon?: string | ReactNode;
    rewindIcon?: string | ReactNode;
    forwardIcon?: string | ReactNode;
    hideControlsDelay?: number;
    loop?: boolean;
    muted?: boolean;
    seekAmount?: number;
    funcss?: string;
    containerCss?: string;
    videoCss?: string;
    controlsCss?: string;
    progressCss?: string;
    progressBarCss?: string;
    timeCss?: string;
    playCss?: string;
    pauseCss?: string;
    volumeCss?: string;
    fullscreenCss?: string;
    downloadCss?: string;
    rewindCss?: string;
    forwardCss?: string;
    buttonCss?: string;
    style?: React.CSSProperties;
    volumeStyle?: 'slider' | 'compact' | 'hover';
    variant?: string;
}
export default function Video({ src, poster, onDuration, onEnded, isPause, spacebarPlay, className, autoPlay, showControls, showPlayPause, showProgress, showVolume, showTime, showFullscreen, showDownload, showSeekButtons, playIcon, pauseIcon, fullscreenIcon, downloadIcon, volumeIcon, muteIcon, rewindIcon, forwardIcon, hideControlsDelay, loop, muted, seekAmount, funcss, containerCss, videoCss, controlsCss, progressCss, progressBarCss, timeCss, playCss, pauseCss, volumeCss, fullscreenCss, downloadCss, rewindCss, forwardCss, buttonCss, volumeStyle, style, variant, ...rest }: VideoProps): React.JSX.Element;
export {};
