import React from 'react';
type VistaProps = {
    layout?: 'centered' | 'imageLeft' | 'imageRight' | 'stacked';
    pattern?: 'grid' | 'dots' | 'diagonal' | 'checkerboard' | 'horizontal' | 'vertical';
    patternOpacity?: number;
    reverse?: boolean;
    bg?: string;
    padding?: string;
    textAlign?: 'left' | 'center' | 'right';
    imgPosition?: 'top' | 'bottom';
    funcss?: string;
    blurry?: number;
    opacity?: number;
    heading?: React.ReactNode;
    headingSize?: string;
    headingWeight?: number;
    headingColor?: string;
    headingClass?: string;
    subheading?: React.ReactNode;
    subheadingSize?: string;
    subheadingWeight?: number;
    subheadingColor?: string;
    subheadingClass?: string;
    content?: React.ReactNode;
    contentSize?: string;
    contentWeight?: number;
    contentColor?: string;
    contentClass?: string;
    image?: React.ReactNode;
    imageUrl?: string;
    imageAlt?: string;
    imageClass?: string;
    imageSize?: string;
    cta?: React.ReactNode;
    ctaClass?: string;
    sectionClass?: string;
    containerClass?: string;
    gap?: string;
    textWrapperClass?: string;
    imageWrapperClass?: string;
    children?: React.ReactNode;
    showGradient?: boolean;
    gradientPosition?: 'top-left' | 'top-right' | 'bottom-left' | 'bottom-right' | 'center';
    gradientSize?: string;
    gradientColors?: string;
    fade?: boolean;
    fadeDirection?: 'top' | 'bottom' | 'left' | 'right';
    fadeRadial?: boolean;
    fadeOverlayDarken?: number;
    backgroundImage?: string;
    variant?: string;
    showPrimaryCTA?: boolean;
    showSecondaryCTA?: boolean;
    showAccentCTA?: boolean;
    primaryButtonOutlined?: boolean;
    secondaryButtonOutlined?: boolean;
    accentButtonOutlined?: boolean;
    ctaPrimaryUrl?: string;
    ctaSecondaryUrl?: string;
    ctaAccentUrl?: string;
    ctaPrimaryText?: string;
    ctaSecondaryText?: string;
    ctaAccentText?: string;
    ctaPrimaryRounded?: boolean;
    ctaPrimaryFlat?: boolean;
    ctaPrimaryPrefix?: string;
    ctaPrimarySuffix?: string;
    primaryIconSize?: number;
    ctaSecondaryRounded?: boolean;
    ctaSecondaryFlat?: boolean;
    ctaSecondaryPrefix?: string;
    ctaSecondarySuffix?: string;
    secondaryIconSize?: number;
    ctaAccentRounded?: boolean;
    ctaAccentFlat?: boolean;
    ctaAccentPrefix?: string;
    ctaAccentSuffix?: string;
    accentIconSize?: number;
    ctaGap?: number;
    ctaFlexJustify?: 'flex-start' | 'center' | 'flex-end' | 'space-between' | 'space-around';
};
declare const Vista: React.FC<VistaProps>;
export default Vista;
