import React from 'react';
type VistaProps = {
    layout?: 'centered' | 'mediaLeft' | 'mediaRight' | 'stacked';
    pattern?: 'grid' | 'dots' | 'diagonal' | 'checkerboard' | 'horizontal' | 'vertical';
    patternOpacity?: number;
    reverse?: boolean;
    bg?: string;
    padding?: string;
    textAlign?: 'left' | 'center' | 'right';
    mediaPosition?: 'top' | 'bottom';
    funcss?: string;
    blurry?: number;
    opacity?: number;
    heading?: React.ReactNode;
    headingSize?: string;
    headingWeight?: number;
    headingColor?: string;
    headingClass?: string;
    subheading?: React.ReactNode;
    subheadingSize?: string;
    subheadingWeight?: number;
    subheadingColor?: string;
    subheadingClass?: string;
    content?: React.ReactNode;
    contentSize?: string;
    contentWeight?: number;
    contentColor?: string;
    contentClass?: string;
    media?: React.ReactNode;
    mediaUrl?: string;
    mediaAlt?: string;
    mediaClass?: string;
    mediaSize?: string;
    cta?: React.ReactNode;
    ctaClass?: string;
    sectionClass?: string;
    containerClass?: string;
    gap?: string;
    textWrapperClass?: string;
    mediaWrapperClass?: string;
    children?: React.ReactNode;
    showGradient?: boolean;
    gradientPosition?: 'top-left' | 'top-right' | 'bottom-left' | 'bottom-right' | 'center';
    gradientSize?: string;
    gradientColors?: string;
    fade?: boolean;
    fadeColor?: string;
    fadeDirection?: 'top' | 'bottom' | 'left' | 'right';
    fadeRadial?: boolean;
    variant?: string;
    mediaCss?: string;
    showPrimaryCTA?: boolean;
    showSecondaryCTA?: boolean;
    showAccentCTA?: boolean;
    primaryButtonOutlined?: boolean;
    secondaryButtonOutlined?: boolean;
    accentButtonOutlined?: boolean;
    ctaPrimaryUrl?: string;
    ctaSecondaryUrl?: string;
    ctaAccentUrl?: string;
    ctaPrimaryText?: string;
    ctaSecondaryText?: string;
    ctaAccentText?: string;
    ctaPrimaryRounded?: boolean;
    ctaPrimaryFlat?: boolean;
    ctaPrimaryPrefix?: string;
    ctaPrimarySuffix?: string;
    primaryIconSize?: number;
    primaryButtonFuncss?: string;
    primaryButtonSmall?: boolean;
    ctaSecondaryRounded?: boolean;
    ctaSecondaryFlat?: boolean;
    ctaSecondaryPrefix?: string;
    ctaSecondarySuffix?: string;
    secondaryIconSize?: number;
    secondaryButtonFuncss?: string;
    secondaryButtonSmall?: boolean;
    ctaAccentRounded?: boolean;
    ctaAccentFlat?: boolean;
    ctaAccentPrefix?: string;
    ctaAccentSuffix?: string;
    accentIconSize?: number;
    accentButtonFuncss?: string;
    accentButtonSmall?: boolean;
    ctaGap?: number;
    ctaFlexJustify?: 'flex-start' | 'center' | 'flex-end' | 'space-between' | 'space-around';
    mediaType?: 'image' | 'video' | 'iframe' | 'custom';
    videoUrl?: string;
    videoAutoplay?: boolean;
    videoLoop?: boolean;
    videoMuted?: boolean;
    videoPoster?: string;
    videoControls?: boolean;
    iframeUrl?: string;
    iframeSize?: string;
    customMedia?: React.ReactNode;
    mediaOverlay?: boolean;
    mediaOverlayColor?: string;
    mediaOverlayOpacity?: number;
    mediaFilter?: 'grayscale' | 'sepia' | 'blur' | 'brightness' | 'contrast' | 'none';
    mediaFilterValue?: number;
    mediaBlendMode?: 'multiply' | 'screen' | 'overlay' | 'darken' | 'lighten';
    hoverEffect?: 'lift' | 'scale' | 'tilt' | 'glow' | 'none';
    parallax?: boolean;
    parallaxSpeed?: number;
};
declare const Vista: React.FC<VistaProps>;
export default Vista;
