import React from 'react';
type VistaProps = {
    layout?: 'centered' | 'imageLeft' | 'imageRight' | 'stacked';
    pattern?: 'grid' | 'dots' | 'diagonal' | 'checkerboard' | 'horizontal' | 'vertical';
    patternOpacity?: number;
    reverse?: boolean;
    bg?: string;
    padding?: string;
    textAlign?: 'left' | 'center' | 'right';
    imgPosition?: 'top' | 'bottom';
    funcss?: string;
    blurry?: number;
    opacity?: number;
    heading?: React.ReactNode;
    subheading?: React.ReactNode;
    content?: React.ReactNode;
    image?: React.ReactNode;
    cta?: React.ReactNode;
    sectionClass?: string;
    containerClass?: string;
    textWrapperClass?: string;
    imageWrapperClass?: string;
    children?: React.ReactNode;
    showGradient?: boolean;
    gradientPosition?: 'top-left' | 'top-right' | 'bottom-left' | 'bottom-right' | 'center';
    gradientSize?: string;
    gradientColors?: string;
    fade?: boolean;
    fadeDirection?: 'top' | 'bottom' | 'left' | 'right';
    fadeRadial?: boolean;
    fadeOverlayDarken?: number;
    backgroundImage?: string;
};
declare const Vista: React.FC<VistaProps>;
export default Vista;
