import React from 'react';
export type Product = {
    id: string;
    name: string;
    price: number;
    comparePrice?: number;
    description?: string;
    images?: string[];
    category?: string;
    brand?: string;
    tags?: string[];
    colors?: {
        name: string;
        code: string;
    }[];
    sku?: string;
    stock?: number;
    rating?: number;
    isNew?: boolean;
    isSale?: boolean;
    discountPercentage?: number;
};
export type CartItem = {
    product: Product;
    quantity: number;
    selectedColor?: string;
};
type ProductsPageProps = {
    products: Product[] | string;
    title?: string;
    showHeader?: boolean;
    showSearch?: boolean;
    showFilters?: boolean;
    showCart?: boolean;
    cartIcon?: string | React.ReactNode;
    cartBadgeColor?: string;
    cartBadgeText?: string;
    checkoutText?: string;
    checkoutIcon?: string | React.ReactNode;
    onAddToCart?: (item: CartItem) => void;
    onRemoveFromCart?: (itemId: string) => void;
    onUpdateQuantity?: (itemId: string, quantity: number) => void;
    onCheckout?: (cartItems: CartItem[], totalAmount: number) => void;
    onProductClick?: (product: Product) => void;
    className?: string;
    gridClassName?: string;
    children?: React.ReactNode;
    style?: React.CSSProperties;
    id?: string;
    funcss?: string;
    bg?: string;
    color?: string;
    rounded?: boolean;
    raised?: boolean;
    fullWidth?: boolean;
    small?: boolean;
    big?: boolean;
};
declare const Products: React.FC<ProductsPageProps>;
export default Products;
