import React from 'react';
export type WeightUnit = 'g' | 'kg' | 'oz' | 'lb';
export type DimensionUnit = 'cm' | 'm' | 'in' | 'ft';
export interface ProductVariant {
    id: string;
    name: string;
    sku?: string;
    price: number;
    comparePrice?: number;
    currency?: string;
    weight?: number;
    weightUnit?: WeightUnit;
    stock?: number;
    images?: string[];
    color?: string;
    size?: string;
    discount?: number;
}
export type Product = {
    id: string;
    name: string;
    price: number;
    comparePrice?: number;
    currency?: string;
    description?: string;
    images?: string[];
    category?: string;
    brand?: string;
    tags?: string[];
    colors?: {
        name: string;
        code: string;
    }[];
    sizes?: string[];
    weight?: number;
    weightUnit?: WeightUnit;
    sku?: string;
    stock?: number;
    rating?: number;
    isNew?: boolean;
    isSale?: boolean;
    variants?: ProductVariant[];
    manufacturer: string | '';
    countryOfOrigin: string | '';
    warranty: string | '';
    isFeatured: string | '';
    discount?: number;
};
export type CartItem = {
    product: Product;
    variant?: ProductVariant;
    quantity: number;
    selectedColor?: string;
    selectedSize?: string;
    addedAt: number;
    originalPrice?: number;
};
export type CartStorage = {
    items: CartItem[];
    updatedAt: number;
};
type ProductsPageProps = {
    products?: Product[] | string;
    bucket?: string;
    bucketPage?: number;
    bucketSize?: number;
    title?: string;
    showHeader?: boolean;
    showSearch?: boolean;
    showFilters?: boolean;
    showCart?: boolean;
    cartIcon?: string | React.ReactNode;
    cartBadgeColor?: string;
    cartBadgeText?: string;
    checkoutText?: string;
    checkoutIcon?: string | React.ReactNode;
    currency?: string;
    persistCart?: boolean;
    storageKey?: string;
    onAddToCart?: (item: CartItem) => void;
    onRemoveFromCart?: (itemId: string) => void;
    onUpdateQuantity?: (itemId: string, quantity: number) => void;
    onCheckout?: (cartItems: CartItem[], totalAmount: number) => void;
    onProductClick?: (product: Product) => void;
    className?: string;
    gridClassName?: string;
    children?: React.ReactNode;
    id?: string;
    funcss?: string;
    bg?: string;
    color?: string;
    fullWidth?: boolean;
    small?: boolean;
    big?: boolean;
    itemsPerPage?: number;
    variant?: string;
};
declare const Store: React.FC<ProductsPageProps>;
export default Store;
