import * as React from 'react';
type ViewProps = {
    children?: React.ReactNode;
    content?: React.ReactNode;
    funcss?: string;
    customStyle?: React.CSSProperties;
    height?: string;
    width?: string;
    minHeight?: string;
    maxHeight?: string;
    minWidth?: string;
    maxWidth?: string;
    padding?: string;
    margin?: string;
    gap?: string;
    fit?: boolean;
    display?: React.CSSProperties['display'];
    flexDirection?: React.CSSProperties['flexDirection'];
    justifyContent?: React.CSSProperties['justifyContent'];
    alignItems?: React.CSSProperties['alignItems'];
    background?: string;
    color?: string;
    border?: string;
    borderRadius?: string;
    boxShadow?: string;
    position?: React.CSSProperties['position'];
    top?: string;
    left?: string;
    right?: string;
    bottom?: string;
    zIndex?: number;
    overflow?: React.CSSProperties['overflow'];
    id?: string;
    title?: string;
    role?: string;
    ariaLabel?: string;
    onClick?: React.MouseEventHandler<HTMLDivElement>;
    onMouseEnter?: React.MouseEventHandler<HTMLDivElement>;
    onMouseLeave?: React.MouseEventHandler<HTMLDivElement>;
    onFocus?: React.FocusEventHandler<HTMLDivElement>;
    onBlur?: React.FocusEventHandler<HTMLDivElement>;
};
declare const View: ({ children, content, funcss, customStyle, height, width, minHeight, maxHeight, minWidth, maxWidth, padding, margin, gap, fit, display, flexDirection, justifyContent, alignItems, background, color, border, borderRadius, boxShadow, position, top, left, right, bottom, zIndex, overflow, id, title, role, ariaLabel, onClick, onMouseEnter, onMouseLeave, onFocus, onBlur, ...rest }: ViewProps) => React.JSX.Element;
export default View;
