import React, { CSSProperties, HTMLAttributes, ReactNode } from 'react';
interface ViewProps extends Omit<HTMLAttributes<HTMLDivElement>, 'content'> {
    children?: ReactNode;
    content?: ReactNode;
    funcss?: string;
    customStyle?: CSSProperties;
    height?: string | number;
    width?: string | number;
    minHeight?: string | number;
    maxHeight?: string | number;
    minWidth?: string | number;
    maxWidth?: string | number;
    padding?: string | number;
    margin?: string | number;
    gap?: string | number;
    fit?: boolean;
    display?: CSSProperties['display'];
    flexDirection?: CSSProperties['flexDirection'];
    justifyContent?: CSSProperties['justifyContent'];
    alignItems?: CSSProperties['alignItems'];
    bg?: string;
    borderRadius?: string;
    boxShadow?: string;
    position?: CSSProperties['position'];
    top?: string | number;
    left?: string | number;
    right?: string | number;
    bottom?: string | number;
    zIndex?: number;
    overflow?: string;
}
declare function View(props: ViewProps): React.JSX.Element;
export default View;
