import React, { ReactNode, MouseEvent } from 'react';
interface ButtonProps {
    color?: string;
    bg?: string;
    funcss?: string;
    startIcon?: ReactNode;
    endIcon?: ReactNode;
    stringPrefix?: string;
    stringSuffix?: string;
    prefix?: ReactNode;
    suffix?: ReactNode;
    iconSize?: number | string;
    iconLineHeight?: string | number;
    text?: string;
    rounded?: boolean;
    raised?: boolean;
    height?: string;
    width?: string;
    float?: boolean;
    hoverUp?: boolean;
    fullWidth?: boolean;
    outlined?: boolean;
    small?: boolean;
    hoverless?: boolean;
    smaller?: boolean;
    big?: boolean;
    bigger?: boolean;
    jumbo?: boolean;
    flat?: boolean;
    hoverNone?: boolean;
    fillAnimation?: boolean;
    bold?: boolean;
    fillDirection?: string;
    fillTextColor?: string;
    buttonFillStyle?: React.CSSProperties;
    outlineSize?: number;
    isLoading?: boolean;
    variant?: string;
    url?: string;
    status?: 'success' | 'warning' | 'info' | 'danger';
    children?: React.ReactNode;
    style?: React.CSSProperties;
    onClick?: (event: MouseEvent<HTMLButtonElement>) => void;
}
export default function Button({ variant, color, bg, funcss, startIcon, endIcon, stringPrefix, stringSuffix, prefix, suffix, iconSize, iconLineHeight, text, rounded, raised, height, width, float, hoverUp, fullWidth, outlined, small, hoverless, smaller, big, bigger, jumbo, flat, hoverNone, fillAnimation, fillDirection, fillTextColor, outlineSize, isLoading, status, bold, children, style, url, onClick, ...rest }: ButtonProps): React.JSX.Element;
export {};
