import { ReactNode } from 'react';
import * as React from 'react';
interface ButtonProps {
    color?: string;
    bg?: string;
    funcss?: string;
    startIcon?: ReactNode;
    endIcon?: ReactNode;
    text?: string;
    rounded?: boolean;
    raised?: boolean;
    height?: string;
    width?: string;
    float?: boolean;
    hoverUp?: boolean;
    fullWidth?: boolean;
    outlined?: boolean;
    small?: boolean;
    smaller?: boolean;
    big?: boolean;
    bigger?: boolean;
    jumbo?: boolean;
    flat?: boolean;
    hoverNone?: boolean;
    fillAnimation?: boolean;
    bold?: boolean;
    hoverless?: boolean;
    fillDirection?: string;
    fillTextColor?: string;
    buttonFillStyle?: React.CSSProperties;
    outlineSize?: number;
    isLoading?: boolean;
    status?: 'success' | 'warning' | 'info' | 'danger';
    children?: React.ReactNode;
    style?: React.CSSProperties;
    onClick?: (...args: unknown[]) => void;
}
export default function Button({ color, bg, funcss, startIcon, endIcon, text, rounded, raised, height, width, float, hoverUp, fullWidth, outlined, small, hoverless, smaller, big, bigger, jumbo, flat, hoverNone, fillAnimation, fillDirection, fillTextColor, outlineSize, isLoading, status, children, bold, style, onClick, ...rest }: ButtonProps): React.JSX.Element;
export {};
