import * as React from 'react';
type TypographyProps = {
    id?: string;
    size?: "smaller" | "small" | "big" | "bigger" | "jumbo" | "minified";
    bg?: string;
    color?: string;
    children?: React.ReactNode;
    hoverBg?: string;
    monospace?: boolean;
    hoverText?: string;
    text?: string;
    heading?: "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
    funcss?: string;
    emp?: boolean;
    bold?: boolean;
    block?: boolean;
    body?: boolean;
    article?: boolean;
    light?: boolean;
    lighter?: boolean;
    italic?: boolean;
    underline?: boolean;
    quote?: boolean;
    align?: "left" | "center" | "right" | "justify";
    lineHeight?: string;
    letterSpacing?: string;
    uppercase?: boolean;
    lowercase?: boolean;
    capitalize?: boolean;
    textDecoration?: "none" | "underline" | "overline" | "line-through";
    textTransform?: "none" | "capitalize" | "uppercase" | "lowercase";
    whiteSpace?: "normal" | "nowrap" | "pre" | "pre-line" | "pre-wrap";
    wordBreak?: "normal" | "break-all" | "keep-all" | "break-word";
    fontFamily?: string;
    textShadow?: string;
    textAlign?: "left" | "center" | "right" | "justify";
    opacity?: number;
    zIndex?: number;
    transform?: string;
    customStyles?: React.CSSProperties;
    onClick?: () => void;
};
export default function Text({ id, size, bg, color, children, hoverBg, hoverText, text, heading, funcss, emp, bold, block, body, article, light, lighter, italic, underline, align, lineHeight, letterSpacing, uppercase, lowercase, capitalize, textDecoration, textTransform, whiteSpace, wordBreak, fontFamily, textShadow, textAlign, opacity, zIndex, transform, customStyles, monospace, quote, ...rest }: TypographyProps): any;
export {};
