import * as React from 'react';
type TypographyProps = {
    id?: string;
    size?: string;
    bg?: string;
    color?: string;
    children?: React.ReactNode;
    hoverBg?: string;
    hoverText?: string;
    text?: string;
    heading?: string;
    funcss?: string;
    emp?: boolean;
    bold?: boolean;
    block?: boolean;
    body?: boolean;
    article?: boolean;
    light?: boolean;
    lighter?: boolean;
    italic?: boolean;
    underline?: boolean;
    align?: string;
    lineHeight?: string;
    letterSpacing?: string;
    monospace?: boolean;
    customStyles?: React.CSSProperties;
    onClick?: () => void;
};
export default function Text({ id, size, bg, color, children, hoverBg, hoverText, text, heading, funcss, emp, bold, block, body, article, light, lighter, italic, underline, align, lineHeight, letterSpacing, monospace, customStyles, onClick, }: TypographyProps): React.JSX.Element;
export {};
