import * as React from 'react';
type TypographyProps = {
    id?: string;
    size?: "smaller" | "small" | "big" | "bigger" | "jumbo";
    bg?: string;
    color?: "color";
    children?: React.ReactNode;
    hoverBg?: string;
    hoverText?: "color";
    text?: string;
    heading?: "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
    funcss?: "className";
    emp?: boolean;
    bold?: boolean;
    block?: boolean;
    body?: boolean;
    article?: boolean;
    light?: boolean;
    lighter?: boolean;
    italic?: boolean;
    underline?: boolean;
    align?: string;
    lineHeight?: string;
    letterSpacing?: string;
    monospace?: boolean;
    customStyles?: React.CSSProperties;
    onClick?: () => void;
};
export default function Text({ id, size, bg, color, children, hoverBg, hoverText, text, heading, funcss, emp, bold, block, body, article, light, lighter, italic, underline, align, lineHeight, letterSpacing, monospace, customStyles, ...rest }: TypographyProps): any;
export {};
