import React from 'react';
type FeatureItem = {
    icon?: string | React.ReactNode;
    iconColor?: string;
    iconSize?: number;
    iconClassName?: string;
    title?: React.ReactNode;
    titleSize?: string;
    titleWeight?: number;
    titleColor?: string;
    titleClassName?: string;
    titleVariant?: string;
    description?: React.ReactNode;
    descriptionSize?: string;
    descriptionWeight?: number;
    descriptionColor?: string;
    descriptionClassName?: string;
    descriptionVariant?: string;
    imageUrl?: string;
    imageAlt?: string;
    imageClassName?: string;
    imageStyle?: React.CSSProperties;
    content?: React.ReactNode;
    className?: string;
    style?: React.CSSProperties;
    cardBg?: string;
    cardPadding?: string;
    cardRounded?: string;
    cardShadow?: 'sm' | 'md' | 'lg' | 'xl' | 'none';
    cardBorder?: boolean;
    cardBorderColor?: string;
    cardHoverEffect?: 'lift' | 'glow' | 'scale' | 'none';
    ctaText?: string;
    ctaUrl?: string;
    ctaVariant?: 'primary' | 'secondary' | 'accent' | 'text' | 'outline';
    ctaOnClick?: () => void;
    ctaCss?: string;
    ctaClassName?: string;
    customRender?: () => React.ReactNode;
};
type FeatureProps = {
    variant?: string;
    layout?: 'checklist' | 'centered' | 'grid';
    title?: React.ReactNode;
    titleSize?: string;
    titleWeight?: number;
    titleColor?: string;
    titleClassName?: string;
    titleAlign?: 'left' | 'center' | 'right';
    titleVariant?: string;
    subtitle?: React.ReactNode;
    subtitleSize?: string;
    subtitleWeight?: number;
    subtitleColor?: string;
    subtitleClassName?: string;
    subtitleVariant?: string;
    description?: React.ReactNode;
    descriptionSize?: string;
    descriptionWeight?: number;
    descriptionColor?: string;
    descriptionClassName?: string;
    descriptionVariant?: string;
    features?: FeatureItem[] | string;
    columns?: number;
    gap?: string;
    itemGap?: string;
    align?: 'start' | 'center' | 'end' | 'stretch';
    justify?: 'start' | 'center' | 'end' | 'between' | 'around';
    wrap?: boolean;
    bg?: string;
    padding?: string;
    className?: string;
    style?: React.CSSProperties;
    containerClassName?: string;
    containerStyle?: React.CSSProperties;
    cardBg?: string;
    cardPadding?: string;
    cardRounded?: string;
    cardShadow?: 'sm' | 'md' | 'lg' | 'xl' | 'none';
    cardBorder?: boolean;
    cardBorderColor?: string;
    cardHoverEffect?: 'lift' | 'glow' | 'scale' | 'none';
    cardClassName?: string;
    iconColor?: string;
    iconSize?: number;
    iconClassName?: string;
    itemTitleSize?: string;
    itemTitleWeight?: number;
    itemTitleColor?: string;
    itemTitleVariant?: string;
    itemDescriptionSize?: string;
    itemDescriptionWeight?: number;
    itemDescriptionColor?: string;
    itemDescriptionVariant?: string;
    checkmarkIcon?: string;
    checkmarkColor?: string;
    checkmarkSize?: number;
    checkmarkClassName?: string;
    ctaText?: string;
    ctaUrl?: string;
    ctaVariant?: 'primary' | 'secondary' | 'accent' | 'text' | 'outline';
    ctaOnClick?: () => void;
    ctaClassName?: string;
    ctaCss?: string;
    ctaAlign?: 'left' | 'center' | 'right';
    ctaStringPrefix?: string;
    ctaStringSuffix?: string;
    ctaStartIcon?: React.ReactNode;
    ctaEndIcon?: React.ReactNode;
    ctaIconSize?: number;
    ctaIsLoading?: boolean;
    ctaStatus?: 'success' | 'warning' | 'info' | 'error';
    pattern?: 'grid' | 'dots' | 'diagonal' | 'none';
    patternOpacity?: number;
    patternColor?: string;
    patternSize?: string;
    fade?: boolean;
    fadeColor?: string;
    fadeDirection?: 'top' | 'bottom' | 'left' | 'right';
    fadeRadial?: boolean;
    hoverEffect?: 'lift' | 'glow' | 'scale' | 'none';
    children?: React.ReactNode;
    id?: string;
    funcss?: string;
    sectionClass?: string;
    maxWidth?: string;
    responsiveColumns?: string;
};
declare const Feature: React.FC<FeatureProps>;
export default Feature;
