import React from 'react';
type LinkItem = {
    label: string;
    url: string;
    external?: boolean;
    icon?: string;
};
type LinkSection = {
    title: string;
    links: LinkItem[];
};
type SocialMedia = {
    facebook?: React.ReactNode | string;
    instagram?: React.ReactNode | string;
    twitter?: React.ReactNode | string;
    x?: React.ReactNode | string;
    youtube?: React.ReactNode | string;
    linkedin?: React.ReactNode | string;
    github?: React.ReactNode | string;
    [key: string]: React.ReactNode | string | undefined;
};
type FooterProps = {
    logo?: React.ReactNode;
    logoUrl?: string;
    logoSize?: string;
    logoClass?: string;
    logoLinkUrl?: string;
    companyName?: string;
    description?: React.ReactNode | string;
    descriptionClass?: string;
    descriptionVariant?: string;
    year?: number | string;
    showYear?: boolean;
    showRightsReserved?: boolean;
    copyrightText?: string;
    sections?: LinkSection[] | string;
    privacyUrl?: string;
    termsUrl?: string;
    cookiesUrl?: string;
    privacyText?: string;
    termsText?: string;
    cookiesText?: string;
    facebookUrl?: string;
    instagramUrl?: string;
    twitterUrl?: string;
    xUrl?: string;
    youtubeUrl?: string;
    linkedinUrl?: string;
    githubUrl?: string;
    facebookIcon?: React.ReactNode | string;
    instagramIcon?: React.ReactNode | string;
    twitterIcon?: React.ReactNode | string;
    xIcon?: React.ReactNode | string;
    youtubeIcon?: React.ReactNode | string;
    linkedinIcon?: React.ReactNode | string;
    githubIcon?: React.ReactNode | string;
    socialMedia?: SocialMedia;
    socialIconSize?: number;
    email?: string;
    phone?: string;
    address?: string;
    showContactInfo?: boolean;
    emailIcon?: React.ReactNode | string;
    phoneIcon?: React.ReactNode | string;
    addressIcon?: React.ReactNode | string;
    bg?: string;
    textColor?: string;
    borderColor?: string;
    linkHoverColor?: string;
    layout?: 'default' | 'centered' | 'compact' | 'stacked';
    showDivider?: boolean;
    padding?: string;
    gap?: string;
    maxWidth?: string;
    mobileBreakpoint?: string;
    tabletBreakpoint?: string;
    funcss?: string;
    containerClass?: string;
    topSectionClass?: string;
    bottomSectionClass?: string;
    sectionTitleClass?: string;
    linkClass?: string;
    socialContainerClass?: string;
    legalLinksClass?: string;
    children?: React.ReactNode;
    variant?: string;
};
declare const Footer: React.FC<FooterProps>;
export default Footer;
